name: bevfusion
channels:
  - defaults
  - conda-forge
  - pytorch
dependencies:
  - python=3.8
  - pytorch=1.10.1
  - torchvision=0.11.2
  - torchaudio=0.10.1
  - cudatoolkit=11.3
  - pillow=8.4.0
  - tqdm
  - mpi4py=3.0.3
  - numba=0.48.0
  - pip
  - pip:
    - 'numpy<1.20'
    - nuscenes-devkit
    - torchpack
    - mmcv==1.4.0
    - mmcv-full==1.4.0
    - mmdet==2.20.0
    - flash-attn==0.2.0